module.exports = Object.freeze({
    ERROR_CODE_NO_CALLLOGS: 'TEJAC0401',
    ERROR_CODE_X_USER_ID: 'TEJAC0402',
    ERROR_CODE_X_FACE_ID: 'TEJAC0403',
    ERROR_CODE_X_CONTACT_ID: 'TEJAC0404',
    ERROR_CODE_DVCID: 'TEJAC0406',
    ERROR_CODE_PHONE_NO: 'TEJAC0407',
    ERROR_CODE_DATETIME: 'TEJAC0408',
    ERROR_CODE_CALLTYPE: 'TEJAC0409',
    ERROR_CODE_FROM_DATETIME: 'TEJAC0410',
    ERROR_CODE_X_CHUNK_SIZE: 'TEJAC0411',
    ERROR_CODE_BATCH_LIMIT: 'TEJAC0412',
    ERROR_CODE_INVALID_JSON_BODY: 'TEJAC0413',
    ERROR_CODE_DVC_LIST: 'TEJAC0415',
    ERROR_INTERNAL_SERVER_ERROR_FROM_CASSANDRA: 'TEJAC0500',
    ERROR_FROM_AWS: 'TEJAC0501'
});
