module.exports = Object.freeze({

    ERROR_CODE_X_USER_ID: 'TEJAC0401',
    ERROR_CODE_X_FACE_ID: 'TEJAC0402',
    ERROR_CODE_X_S3_KEY: 'TEJAC0403',
    ERROR_CODE_X_S3_BUCKET: 'TEJAC0404',
    ERROR_CODE_X_EXT: 'TEJAC0405',
    ERROR_CODE_X_CONTACT_ID: 'TEJAC0406',
    ERROR_INTERNAL_SERVER_ERROR_FROM_CASSANDRA: 'TEJAC0500',
    ERROR_FROM_AWS: 'TEJAC0501'
});
